spring:
  datasource:
    url: jdbc:h2:mem:${DB_NAME_TEST};DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: ${DB_USER_TEST}
    password: ${DB_PASSWORD_TEST}

  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: WARN
    org.springframework.test: INFO
