spring:
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME_PROD}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER_PROD}
    password: ${DB_PASSWORD_PROD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    schema: ${DB_NAME_PROD}
    clean-disabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
  file:
    name: /var/log/bookstore/bookstore.log

server:
  port: ${SERVER_PORT}