spring:
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME_DEV}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    schema: ${DB_NAME_DEV}

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor: TRACE

server:
  port: 8081
