spring:
  datasource:
    url: jdbc:tc:postgresql:16://bookstore_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

management:
  health:
    mail:
      enabled: false

logging:
  level:
    root: WARN
    com.bookstore: INFO
