-- ======================
-- Online Bookstore
-- ======================

-- Development
CREATE DATABASE IF NOT EXISTS ${DB_NAME_DEV} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER_DEV}'@'%' IDENTIFIED BY '${DB_PASSWORD_DEV}';
GRANT ALL PRIVILEGES ON ${DB_NAME_DEV}.* TO '${DB_USER_DEV}'@'%';

-- Test
CREATE DATABASE IF NOT EXISTS ${DB_NAME_TEST} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER_TEST}'@'%' IDENTIFIED BY '${DB_PASSWORD_TEST}';
GRANT ALL PRIVILEGES ON ${DB_NAME_TEST}.* TO '${DB_USER_TEST}'@'%';

-- Production
CREATE DATABASE IF NOT EXISTS ${DB_NAME_PROD} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER_PROD}'@'%' IDENTIFIED BY '${DB_PASSWORD_PROD}';
GRANT ALL PRIVILEGES ON ${DB_NAME_PROD}.* TO '${DB_USER_PROD}'@'%';

FLUSH PRIVILEGES;
